const categories = [
    { name: "Electronics" },
    { name: "Books" },
    { name: "Fashion" },
    { name: "Automobiles" },
    { name: "Furniture" },
    { name: "Sports" },
    { name: "Health" },
    { name: "Beauty" },
    { name: "Toys" },
    { name: "Groceries" },
    { name: "Gardening" },
    { name: "Home Decor" },
    { name: "Appliances" },
    { name: "Jewelry" },
    { name: "Footwear" },
    { name: "Music" },
    { name: "Movies" },
    { name: "Pet Supplies" },
    { name: "Office Supplies" },
    { name: "Tools" },
    { name: "Travel" },
    { name: "Stationery" },
    { name: "Photography" },
    { name: "Software" },
    { name: "Video Games" },
    { name: "Collectibles" },
    { name: "Crafts" },
    { name: "Baby Products" },
    { name: "Outdoors" },
    { name: "Watches" },
    { name: "Bags" },
    { name: "Bicycles" },
    { name: "Cleaning Supplies" },
    { name: "Kitchen" },
    { name: "Cell Phones" },
    { name: "Networking" },
    { name: "Cameras" },
    { name: "Fitness" },
    { name: "Medical Supplies" },
    { name: "Lighting" },
    { name: "Bathroom Supplies" },
    { name: "Hardware" },
    { name: "Safety" },
    { name: "Bedding" },
    { name: "Educational" },
    { name: "Hiking" },
    { name: "Camping" },
    { name: "Surfing" },
    { name: "Fishing" },
    { name: "Hunting" },
    { name: "Diving" },
    { name: "Winter Sports" },
    { name: "Water Sports" },
    { name: "Mountain Biking" },
    { name: "Running" },
    { name: "Yoga" },
    { name: "Meditation" },
    { name: "Cooking" },
    { name: "Food and Beverages" },
    { name: "Bakery" },
    { name: "Dairy" },
    { name: "Meat" },
    { name: "Seafood" },
    { name: "Frozen Foods" },
    { name: "Snacks" },
    { name: "Condiments" },
    { name: "Beverages" },
    { name: "Coffee" },
    { name: "Tea" },
    { name: "Cereal" },
    { name: "Grains" },
    { name: "Pasta" },
    { name: "Rice" },
    { name: "Nuts" },
    { name: "Spices" },
    { name: "Herbs" },
    { name: "Oil" },
    { name: "Sauces" },
    { name: "Baking Ingredients" },
    { name: "Supplements" },
    { name: "Personal Care" },
    { name: "Hair Care" },
    { name: "Skin Care" },
    { name: "Perfumes" },
    { name: "Makeup" },
    { name: "Shaving" },
    { name: "Deodorants" },
    { name: "Oral Care" },
    { name: "Pain Relief" },
    { name: "Antiseptics" },
    { name: "Bandages" },
    { name: "Pharmacy" },
    { name: "Eyewear" },
    { name: "Sunglasses" },
    { name: "Contact Lenses" },
    { name: "Men's Clothing" },
    { name: "Women's Clothing" },
    { name: "Children's Clothing" },
    { name: "Formal Wear" },
    { name: "Casual Wear" },
    { name: "Underwear" },
    { name: "Sleepwear" },
    { name: "Workwear" },
    { name: "Luggage" },
    { name: "Vintage" },
  ];
  const Category = require("./models/category");
    const mongoose = require("mongoose");
  const addCategoriesToDb = async () => {
    try {
      await Category.insertMany(categories);
      console.log("Categories added successfully!");
      mongoose.connection.close(); 
    } catch (error) {
      console.error("Error adding categories:", error);
    }
  };
 module.exports =  addCategoriesToDb;